### PR TITLE
Upgrade go-kit to v0.9.0

### PR DESCRIPTION
**Pull request by jrife**
This PR removes the `replace` directive that replaces go-kit `v0.9.0` with `v0.3.0` and updates the use of the `github.com/go-kit/kit/log` package to be compatible with the APIs supported by `v0.4.0` and beyond.

**What this PR does / why we need it**:
The `v0.3.0` APIs in `github.com/go-kit/kit/log` are incompatible with those in `v0.4.0` and beyond. This makes it impossible to import packages like `kubevirt.io/client-go/kubecli` into other projects where other dependencies rely on newer versions of go-kit (`go mod` will pick the higher version and this results in compilation errors in `kubevirt.io/client-go/log` due to conflicting APIs).

**Which issue(s) this PR fixes**
NONE

**Special notes for your reviewer**:
NONE

**Release note**:
```release-note
Removed go module pinning to an old version (v0.3.0) of github.com/go-kit/kit
```

### CODE REVIEW

**Review by zcahana — COMMENTED** [review]
Hi @jrife and thanks!

Removing this old dependency pinning indeed seems logical, but I'd like to ensure this doesn't break other consumers of kubevirt packages (and particularly, of the kubevirt.io/client-go).

If I get this correctly, other consumers, who may have too explicitly pinned to `github.com/go-kit/kit v0.3.0` for compatibility with kubevirt, will continue to use v0.3.0 for their builds (as long as they don't remove their `replace` directives). Is the way `kubevirt.io/client-go` now uses go-kit's logger compatible with v0.3.0? I think it is but just want to make sure.

I'd also *do* mention this in the PR's release note, so that consumers may have a chance to notice it and update their deps accordingly. Something along the lines of "Removed go module pinning to an old version of github.com/go-kit/kit". Make sure to wrap it in a `release-note` formatting to have the bot satisfied:
````
```release-note

```
````

/lgtm
/ok-to-test

**Comment by jrife** [comment]
Hi @zcahana. Updated the release notes. To add a little more detail, the `go-kit` module seems to have changed the API of the `log` package in an incompatible way between minor versions (`v0.3.0` and `v0.4.0`). Notably, they've removed the `log.Context` type entirely and instead context is added to a structured logger instance using top-level package functions (`log.With`, `log.WithPrefix`):

### `v0.3.0`
```golang
logger := log.NewContext(log.NewJSONLogger(log.NewSyncWriter(os.Stdout))).With("abc", "123")
```

### `v0.4.0`
```golang
logger := log.With(log.NewJSONLogger(log.NewSyncWriter(os.Stdout)), "abc", "123")
```

The way `kubevirt` uses the package right now is compatible with `v0.3.0`. In my PR I update the places that use the `log` package to be compatible with `v0.4.0` and higher. If my module requires (either directly or indirectly) both `kubevirt.io/client-go/log` and some other module that requires `github.com/go-kit/kit/log` at a higher version, say `v0.10.0`, it leads to a compilation error. Because of the way go selects a [module version](https://golang.org/ref/mod#minimal-version-selection)

> MVS starts at the main module (a special vertex in the graph that has no version) and traverses the graph, tracking the highest required version of each module. At the end of the traversal, the highest required versions comprise the build list: they are the minimum versions that satisfy all requirements.

it would try to build everything with the highest minor version of `go-kit` (`v0.10.0`) which doesn't work if `kubevirt.io/client-go/log` is built around the `v0.3.0` API. The root of the problem here is that `go-kit` doesn't correctly use semantic versioning. In the strictest sence, `v0.3.0` and `v0.10.0` *should* have compatible APIs, but alas, they do not.

> If I get this correctly, other consumers, who may have too explicitly pinned to `github.com/go-kit/kit v0.3.0` for compatibility with kubevirt, will continue to use v0.3.0 for their builds (as long as they don't remove their `replace` directives). Is the way `kubevirt.io/client-go` now uses go-kit's logger compatible with v0.3.0? I think it is but just want to make sure.

Because of the breaking change between minor versions code can be compatible with either `v0.3.0` and below or `v0.4.0` and above. With the change in my PR consumers who depend on both `github.com/go-kit/kit/log` at `v0.3.0` or below and `kubevirt.io/client-go/log` would need to update their version of `github.com/go-kit/kit/log` to a newer version and update the use of that package in their code to prevent compilation errors.

**Comment by zcahana** [comment]
Thanks for this detailed explanation @jrife!

> Because of the breaking change between minor versions code can be compatible with either v0.3.0 and below or v0.4.0 and above. With the change in my PR consumers who depend on both github.com/go-kit/kit/log at v0.3.0 or below and kubevirt.io/client-go/log would need to update their version of github.com/go-kit/kit/log to a newer version and update the use of that package in their code to prevent compilation errors.

I still didn't manage to completely figure out whether the change introduced by this PR can be a breaking change to some consumers, and particularly to those who are relying on go-kit v0.3.0 (i.e., they have a similar `replace` directive in their go.mod). 
If I understand it correctly (I'm not sure I do :smile:), as long as they have that `replace` directive, they'll continue to use 0.3.0 (as `replace` directives are honored for the "main" module only, and can force the build to use a version lower than the one required by a dependency (such as kubevirt.io/client-go)). If that's correct (is it?), the our (new) usage of go-kit/log will still be compiled with go-kit v0.3.0. And if that's correct too (is it?), this will compile just fine as the v0.4.0+ API is compatible with v0.3.0 too.

**Comment by jrife** [comment]
> I still didn't manage to completely figure out whether the change introduced by this PR can be a breaking change to some consumers, and particularly to those who are relying on go-kit v0.3.0 (i.e., they have a similar `replace` directive in their go.mod).

This *can* be a breaking change for consumers whose module imports `github.com/go-kit/kit/log` at `v0.3.0` or below directly or whose module imports another module that includes `github.com/go-kit/kit/log` at `v0.3.0` or below in its dependency graph:

### Scenario 1
`my-module` imports `github.com/go-kit/kit/log` in one of its own packages and consumes the API, expecting the behavior supported in `v0.3.0` (e.g. `log.NewContext`).

```
my-module
|
|--github.com/go-kit/kit @ `v0.3.0`
|--kubevirt.io/client-go
```

In this case upgrading to a version of `kubevirt.io/client-go` that includes the change in this PR would require the consumer to update their own use of the `github.com/go-kit/kit/log` package to be compatible with the newer APIs. There is no single version of `go-kit/kit` that satisfies the requirements of code expecting the API from versions <= `v0.3.0` and of code expecting the API from versions > `v0.3.0`.

### Scenario 2
`my-module` imports some other module that in turn imports `github.com/go-kit/kit/log` in one of its own packages and consumes the API, expecting the behavior supported in `v0.3.0` (e.g. `log.NewContext`).

```
my-module
|
|--github.com/some/other/module @ someversion
|  |--github.com/go-kit/kit @ `v0.3.0`
|--kubevirt.io/client-go
```

In this case there is no easy way to resolve this conflict for the maintainer of `my-module`. They would either have to update the version they use of `github.com/some/other/module` to a version that *hopefully* uses `github.com/go-kit/kit` at a higher version, work with the maintainer of `github.com/some/other/module` to upgrade the version, or avoid the use of `github.com/some/other/module` altogether.

> If I understand it correctly (I'm not sure I do 😄), as long as they have that `replace` directive, they'll continue to use 0.3.0 (as `replace` directives are honored for the "main" module only, and can force the build to use a version lower than the one required by a dependency (such as kubevirt.io/client-go)). If that's correct (is it?), the our (new) usage of go-kit/log will still be compiled with go-kit v0.3.0. And if that's correct too (is it?), this will compile just fine as the v0.4.0+ API is compatible with v0.3.0 too.

The `v0.4.0+` API of `github.com/go-kit/kit/log` is *incompatible* with `v0.3.0` and below. The problem isn't so much the version of the module you choose it's that there is no single version of `github.com/go-kit/kit/log` that satisfies the requirements of code expecting the old-style APIs and new-style APIs (i.e. a `replace` directive doesn't help to resolve these conflicts). My original problem (the reason I submitted the PR) basically looks like this:

### My Scenario
```
my-module
|
|--kubevirt.io/client-go @ v0.43.0 <-- Code in `kubevirt.io/client-go/log` expects `v0.3.0` APIs.
|--github.com/some/other/module
|  |--github.com/go-kit/kit @ v0.10.0
```

`my-module` imports `kubevirt.io/client-go/kubecli` which in turn imports `kubevirt.io/client-go/log` which is written around the `v0.3.0` APIs of `github.com/go-kit/kit/log`. It won't compile because the dependency resolution selects `v0.10.0` as the `go-kit` version to use which is incompatible with what `kubevirt.io/client-go/log` expects. If I add a `replace` directive to my `go.mod` file to force go to build using `v0.3.0` this just moves the compilation problem to `github.com/some/other/module` because it expects the newer APIs.

There's no perfect solution here (someone somewhere will always have a compilation error), but my logic behind submitting this PR is that `v0.3.0` is quite old and moving forward it's probably more likely for other modules to be using versions > `v0.3.0` than <= `v0.3.0`. It's probably better to be compatible with the newer versions going forward. Let me know if you agree with the reasoning here, or if you see a better way.

**Comment by rmohr** [comment]
I tried today again to untangle all this a little and just export our golang types and a plane generated client, but failed again. Some of our dependencies pull in a lot of other dependencies. :/

We need to find a general solution for this. No one deserves this kind of dependency hell.

I think we should  settle on a model where all our go types consist of easy to resolve dependencies where one can generate a client with client-gen and just override the few existing kubernetes.io dependencies with the version used in the external projects main `go.mod`.

I could come up pretty easily with changes to generate a stripped down generated client for kubevirt, but the CDI dependencies have `openshift.io` dependencies which makes it a mess again ...

@mhenriks maybe we can discuss this.

**Comment by jrife** [comment]
@rmohr @zcahana I'm not sure what more general solution you have in mind, but one idea I had to solve the problem with this particular dependency is to replace `github.com/go-kit/kit/log` with a different structured logger like `zap`. The root problem in this case is that `github.com/go-kit/kit/log` doesn't really follow semantic versioning properly (`v0.4.0+` should be backwards compatible with `v0.3.0`). If, for example, `go.uber.org/zap` was used instead, which I *think* maintains backwards compatibility through all it's minor versions (`v1.0.0` -> `v1.19.1`), then it would eliminate version conflicts in this package in future releases of `kubevirt.io/client-go`. Since the surface area is small here it seems quite simple to switch out the library. I could submit a PR for this if the Kubevirt team is OK with the idea.

**Comment by rmohr** [comment]
> @rmohr @zcahana I'm not sure what more general solution you have in mind, but one idea I had to solve the problem with this particular dependency is to replace `github.com/go-kit/kit/log` with a different structured logger like `zap`. The root problem in this case is that `github.com/go-kit/kit/log` doesn't really follow semantic versioning properly (`v0.4.0+` should be backwards compatible with `v0.3.0`). If, for example, `go.uber.org/zap` was used instead, which I _think_ maintains backwards compatibility through all it's minor versions (`v1.0.0` -> `v1.19.1`), then it would eliminate version conflicts in this package in future releases of `kubevirt.io/client-go`. Since the surface area is small here it seems quite simple to switch out the library. I could submit a PR for this if the Kubevirt team is OK with the idea.

I would really not mind getting rid or `go-kit/kit/log` but I would prefer if we end up with the same structured logger which k8s is converging to.

In general regarding to fixing the dependency issues, we just discussed this in todays community meeting. @mhenriks and I roughly favoured there a model where we would expose our api structs in separate repos so that one can just use `client-gen` to generate clients and would only have to adjust one or to k8s versions in go.mod.

**Comment by jrife** [comment]
> I would really not mind getting rid or `go-kit/kit/log` but I would prefer if we end up with the same structured logger which k8s is converging to.

This would solve my immediate problem with the `go-kit/kit/log` dependency, and like I said I'd be happy to make the change. What structured logger is k8s converging to? Any links or discussions about this?

> In general regarding to fixing the dependency issues, we just discussed this in todays community meeting. @mhenriks and I roughly favoured there a model where we would expose our api structs in separate repos so that one can just use `client-gen` to generate clients and would only have to adjust one or to k8s versions in go.mod.

This sounds reasonable. If I understand correctly under this model the kubevirt project would only export the structs themselves (e.g. like those in `clieng-go/api/types.go`) and consumers could generate thick clients themselves with `client-gen` using whatever k8s version is suitable thus eliminating a lot of the dependencies currently carried by `client-go`?

**Comment by rmohr** [comment]
> This would solve my immediate problem with the `go-kit/kit/log` dependency, and like I said I'd be happy to make the change. What structured logger is k8s converging to? Any links or discussions about this?
> 
> >

Would be great if you make the switch.

The good new is that it is already in our codebase. The import would be `k8s.io/klog/v2`. A few hints:

* https://kubernetes.io/docs/concepts/cluster-administration/system-logs/
* https://github.com/kubernetes/klog

Note that our logger already co-exists with `glog` and `klog/v1` and we are collecting all the logs from `glog` and `klog/v1` and transform that in our structured logging format. I am not sure how much work it is to continue doing that with `klog/v2`.

> This sounds reasonable. If I understand correctly under this model the kubevirt project would only export the structs themselves (e.g. like those in `clieng-go/api/types.go`) and consumers could generate thick clients themselves with `client-gen` using whatever k8s version is suitable thus eliminating a lot of the dependencies currently carried by `client-go`?

Yes exactly. The best example is https://github.com/kubernetes/api. We would need one repo like this from `cdi` which brings its own dependencies which are hard to resolve and here we would do the same things to eliminate our dependencies. At the end we would have a repo which would almost exclusively depend on 2 or 3 core kubernetes dependencies where you just override the version with your projects version.

File: staging/src/kubevirt.io/client-go/log/log.go [hunk 1]
```diff
@@ -69,7 +69,7 @@ type LoggableObject interface {
 }
 
 type FilteredLogger struct {
-	logContext            *log.Context
```
Comment (rmohr) [inline staging/src/kubevirt.io/client-go/log/log.go:72]: Does the `Context` no longer exist?

**Review by rmohr — APPROVED** [review]
/lgtm
/approve

We should switch to  `klogv2` but we can also take this one in in the meantime if it helps.

File: staging/src/kubevirt.io/client-go/log/log.go (hunk 1 above)
Comment (jrife) [reply staging/src/kubevirt.io/client-go/log/log.go:72]: No. Looking at the [docs](https://pkg.go.dev/github.com/go-kit/kit@v0.4.0/log) it seems like it was removed in `v0.4.0`.
