### PR TITLE
refactor(virtctl/imageupload): set labels using object metadata

### PR DESCRIPTION
**Pull request by codingben**
### What this PR does

Set default labels directly to the object metadata instead of using labels.

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by codingben** [comment]
@0xFelix @lyarwood I plan to use cobra's `cmd.Printf` also. What else should be changed in this PR? do you want also to remove globals and discuss usage of Init() in this PR, or in a separate PR?

**Comment by 0xFelix** [comment]
I am in favor of small and concise PRs

**Comment by codingben** [comment]
> I am in favor of small and concise PRs

Does it mean we should add here only usage of `cmd.Printf` as well?

**Comment by codingben** [comment]
@0xFelix @lyarwood Can you please review?

**Comment by 0xFelix** [comment]
There are compile errors, please have a look.

**Comment by codingben** [comment]
> There are compile errors, please have a look.

This is really weird, because I don't see any compilation errors in my IDE, and not by running `make` commands. I'll take another look tomorrow.

**Comment by xpivarc** [comment]
@codingben you might need to do rebase

**Comment by codingben** [comment]
> @codingben you might need to do rebase

@xpivarc Thanks seems like it worked. Rebase issue caused by https://github.com/kubevirt/kubevirt/pull/12557, but how did you notice about it from the logs?

**Review by 0xFelix — COMMENTED** [review]
/approve
