### ISSUE TITLE
go-client example is not working on kubevirt go-client v0.27.0 

### ISSUE THREAD

**Issue by woohhan** [kubevirt/kubevirt#3188]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
[listvms](https://github.com/kubevirt/kubevirt/tree/master/staging/src/kubevirt.io/client-go/examples/listvms) with go-client version v0.27.0 not working correctly. But it works fine in v0.26.0.

```shell
# kubevirt.io/client-go/log
../../../../pkg/mod/kubevirt.io/client-go@v0.27.0/log/log.go:72:25: undefined: log.Context
```

**What you expected to happen**:
listing vms.

**How to reproduce it (as minimally and precisely as possible)**:
Just using kubevirt.io/client-go package with version v0.27.0

**Anything else we need to know?**:
NONE

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by rmohr** [comment]
Here is another report from a user that it does not work:

```
# kubevirt.io/client-go/kubecli../../pkg/mod/kubevirt.io/client-go@v0.27.0/kubecli/kubevirt_test_utils.go:27:2: cannot use MockKubevirtClientInstance (type *MockKubevirtClient) as type KubevirtClient in return argument:        *MockKubevirtClient does not implement KubevirtClient (missing DiscoveryV1beta1 method) 
```

**Comment by rmohr** [comment]
@woohhan how are you compiling the code? It works for me. What I did is the following on go `1.12.8`:

```
git clone https://github.com/kubevirt/client-go.git
export GO111MODULE=on
cd client-go/
cd client-go/examples/listvms/
go build . # wait for go mod to be finally done
./listvms
```

**Comment by Zizhen** [comment]
@woohhan I ran into your problem too, it seems this lib: github.com/go-kit/kit unexported NewContext in v0.4.0 release 

https://github.com/go-kit/kit/releases/tag/v0.4.0 

I solved it by adding this in go mod github.com/go-kit/kit => github.com/go-kit/kit v0.3.0

**Comment by woohhan** [comment]
@rmohr Thanks for replying. I built similarly, but I modified the client-go version to v0.27.0 in the go.mod file.

**Comment by woohhan** [comment]
@Zizhen Thanks for helping! I added the replacement but looks not working. Could you please share your go.mod file?

**Comment by rmohr** [comment]
@woohhan the steps above worked for me without any modifications. It just takes ages until the dependencies are resovled. Did you try it completely unmodified whith the steps above?

**Comment by woohhan** [comment]
@rmohr It works fine with the above steps without any modifications :) But is the latest version of the kubevirt client not available? As far as I know, the latest version of kubevirt go-client is [v0.27.0](https://github.com/kubevirt/client-go/tree/v0.27.0).

**Comment by rmohr** [comment]
In my steps I checked out the `v0.27.0` tag, so that should exactly be what you want :).

We don't update the `master` branch. We only do releases directly to tags. I think we need to improve the documentation here. I can understand that this can cause confusion.

**Comment by woohhan** [comment]
> In my steps I checked out the `v0.27.0` tag, so that should exactly be what you want :).
> 
> We don't update the `master` branch. We only do releases directly to tags. I think we need to improve the documentation here. I can understand that this can cause confusion.

@rmohr I may be wrong, but `git checkout v0.27.0` doesn't determine what module to be used in `go build`. When we type `go build` command, It downloads the packages what we needed(described in the go.mod file) and builds a binary with the packages. You can check it with the following commands. Please let me know if I am wrong :) Thanks

```
# Delete v0.19.0 client-go
sudo rm -r $GOPATH/pkg/mod/kubevirt.io/client-go@v0.19.0/

# Build again (Same with above)
$ git clone https://github.com/kubevirt/client-go.git
$ export GO111MODULE=on
$ cd client-go/
$ git checkout v0.27.0
$ cd examples/listvms/
$ go build .
go: extracting kubevirt.io/client-go v0.19.0  # It downloads v0.19.0 pkg even though we checked out to v0.27.0
```

**Comment by rmohr** [comment]
That looks strange. When I look at https://github.com/kubevirt/client-go/blob/v0.27.0/go.mod and https://github.com/kubevirt/client-go/blob/v0.27.0/go.sum I don't see any depency to `kubevirt.io/client-go` and also the `go.mod` file says that it is `module kubevirt.io/client-go`.

**Comment by rmohr** [comment]
Oh now I see it. We have this extra `go.mod` file in the example directory. That is not right. Thanks! :+1:

**Comment by mmacheerpuppy** [comment]
I'm getting this with my Gomod as 

`replace k8s.io/client-go => k8s.io/client-go v0.27.2`

Due to this bug  https://github.com/kubernetes/client-go/issues/874
