### PR TITLE
Instancetype: Reintroduce informers in virt controller

### PR DESCRIPTION
**Pull request by lyarwood**
/area instancetype
/cc @rmohr 
/cc @akrejcir 
/cc @davidvossel 

**What this PR does / why we need it**:

The use of these informers was previously removed by
https://github.com/kubevirt/kubevirt/commit/ee4e266dd93b168cc84743a797f64aeb36d75d6b. After further discussions on
the ML [1] however it has become clear that the removal of these
informers from the virt-controller was not required and they can be
reintroduced, this change does this.

The virt-api continues to only use client calls to lookup instancetypes
and preferences.

One small change from the original implementation is that client calls
are now made if an object is not found within an informer. This is to
ensure the object is indeed missing and the failure has not been caused
by a race to update the associated informer.

[1] https://groups.google.com/g/kubevirt-dev/c/q_hR1tFH4Rk

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by lyarwood** [comment]
> > One small change from the original implementation is that client calls
> > are now made if an object is not found within an informer. This is to
> > ensure the object is indeed missing and the failure has not been caused
> > by a race to update the associated informer.
> 
> This looks a little bit strange to me. Is this to avoid a retry due our back-off or are you scared to never retry?

Yeah I didn't think retrying would help here and I did see a similar approach in the PVC protection controller within k8s while researching finalizers a while ago:

https://github.com/kubernetes/kubernetes/blob/09e8339ae4e575ec40e8ed0fc2829fcb678c0f19/pkg/controller/volume/pvcprotection/pvc_protection_controller.go#L211-L227

**Comment by rthallisey** [comment]
@lyarwood performance job isn't working right now.  We're working on fixing

**Comment by lyarwood** [comment]
> @lyarwood performance job isn't working right now. We're working on fixing

ACK thanks and apologies for the noise with the extra runs.

**Comment by rthallisey** [comment]
/test pull-kubevirt-e2e-k8s-1.22-sig-performance

perf job is back up

**Comment by lyarwood** [comment]
Looking positive from the basic numbers in the performance job, I still need to revisit this given the comments by @rmohr but just wanted to highlight things are at least trending in the right direction with the current state of the PR.

[1]  https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/8664/pull-kubevirt-e2e-k8s-1.22-sig-performance/1592152649652768768

```
    "GET-virtualmachineinstancetypes-count": {
      "value": 284.63203333333337
    },
    "GET-virtualmachinepreferences-count": {
      "value": 285.8805888888889
    },
[..]
    "vmiCreationToRunningSecondsP50": {
      "value": 8.570290168727219,
      "thresholdResult": {
        "thresholdValue": 45,
        "thresholdExceeded": false
      }
    },
    "vmiCreationToRunningSecondsP95": {
      "value": 36.999999999999986,
      "thresholdResult": {
        "thresholdValue": 60,
        "thresholdExceeded": false
      }
    },
    "vmiCreationToRunningSecondsP99": {
      "value": 46.80000000000001
    },
```

[2] https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/8537/pull-kubevirt-e2e-k8s-1.22-sig-performance/1591031729479487488 
```
    "GET-virtualmachineinstancetypes-count": {
      "value": 166.82496666666668
    },
    "GET-virtualmachinepreferences-count": {
      "value": 168.23331666666667
    },
[..]
    "vmiCreationToRunningSecondsP50": {
      "value": 6.929857972751119,
      "thresholdResult": {
        "thresholdValue": 45,
        "thresholdExceeded": false
      }
    },
    "vmiCreationToRunningSecondsP95": {
      "value": 17.915179389337094,
      "thresholdResult": {
        "thresholdValue": 60,
        "thresholdExceeded": false
      }
    },
    "vmiCreationToRunningSecondsP99": {
      "value": 25.799999999999994
    },
```

File: pkg/instancetype/instancetype.go [hunk 1]
```diff
@@ -402,12 +413,23 @@ func (m *methods) FindPreferenceSpec(vm *virtv1.VirtualMachine) (*instancetypev1
 }
 
 func (m *methods) getPreferenceSpecRevision(revisionName string, namespace string) (*instancetypev1alpha2.VirtualMachinePreferenceSpec, error) {
-	revision, err := m.clientset.AppsV1().ControllerRevisions(namespace).Get(context.Background(), revisionName, metav1.GetOptions{})
+
```
Comment (0xFelix) [inline pkg/instancetype/instancetype.go:416]: Empty line

File: pkg/instancetype/instancetype.go [hunk 2]
```diff
@@ -421,17 +443,57 @@ func (m *methods) getPreferenceSpecRevision(revisionName string, namespace strin
...
 
+func (m *methods) getControllerRevisionByInformer(revisionName, namespace string) (*appsv1.ControllerRevision, error) {
+	obj, exists, err := m.controllerRevisionStore.GetByKey(namespace + "/" + revisionName)
+	if err != nil {
+		return nil, err
+	}
+	if !exists {
+		return m.getControllerRevisionByClient(revisionName, namespace)
+	}
+	revision := obj.(*appsv1.ControllerRevision)
```
Comment (0xFelix) [inline pkg/instancetype/instancetype.go:454]: Check the cast?

File: pkg/instancetype/instancetype.go [hunk 3]
```diff
@@ -421,17 +443,57 @@ func (m *methods) getPreferenceSpecRevision(revisionName string, namespace strin
...
-	preference, err := m.clientset.VirtualMachinePreference(vm.Namespace).Get(context.Background(), vm.Spec.Preference.Name, metav1.GetOptions{})
+	if m.preferenceStore != nil {
+		return m.findPreferenceByInformer(vm)
+	}
+
+	return m.findPreferenceByClient(vm)
+}
+
+func (m *methods) findPreferenceByInformer(vm *virtv1.VirtualMachine) (*instancetypev1alpha2.VirtualMachinePreference, error) {
+	key := vm.Namespace + "/" + vm.Spec.Preference.Name
```
Comment (0xFelix) [inline pkg/instancetype/instancetype.go:480]: Inline `key` as in `getControllerRevisionByInformer` above?

File: pkg/instancetype/instancetype.go [hunk 4]
```diff
@@ -421,17 +443,57 @@ func (m *methods) getPreferenceSpecRevision(revisionName string, namespace strin
...
+	obj, exists, err := m.preferenceStore.GetByKey(key)
 	if err != nil {
 		return nil, err
 	}
+	if !exists {
+		return m.findPreferenceByClient(vm)
+	}
+	preference := obj.(*instancetypev1alpha2.VirtualMachinePreference)
```
Comment (0xFelix) [inline pkg/instancetype/instancetype.go:488]: Check the cast?

File: pkg/instancetype/instancetype.go [hunk 5]
```diff
@@ -441,6 +503,27 @@ func (m *methods) findClusterPreference(vm *virtv1.VirtualMachine) (*instancetyp
...
 
+	if m.clusterPreferenceStore != nil {
+		return m.findClusterPreferenceByInformer(vm)
+	}
+
+	return m.findClusterPreferenceByClient(vm)
+}
+
+func (m *methods) findClusterPreferenceByInformer(vm *virtv1.VirtualMachine) (*instancetypev1alpha2.VirtualMachineClusterPreference, error) {
+	key := vm.Spec.Preference.Name
```
Comment (0xFelix) [inline pkg/instancetype/instancetype.go:514]: Inline key as above?

File: pkg/instancetype/instancetype.go [hunk 6]
```diff
@@ -441,6 +503,27 @@ func (m *methods) findClusterPreference(vm *virtv1.VirtualMachine) (*instancetyp
...
+	obj, exists, err := m.preferenceStore.GetByKey(key)
+	if err != nil {
+		return nil, err
+	}
+	if !exists {
+		return m.findClusterPreferenceByClient(vm)
+	}
+	preference := obj.(*instancetypev1alpha2.VirtualMachineClusterPreference)
```
Comment (0xFelix) [inline pkg/instancetype/instancetype.go:522]: Check the cast?

File: pkg/instancetype/instancetype.go [hunk 7]
```diff
@@ -503,6 +596,26 @@ func (m *methods) findInstancetype(vm *virtv1.VirtualMachine) (*instancetypev1al
...
+
+func (m *methods) findInstancetypeByInformer(vm *virtv1.VirtualMachine) (*instancetypev1alpha2.VirtualMachineInstancetype, error) {
+	obj, exists, err := m.instancetypeStore.GetByKey(vm.Namespace + "/" + vm.Spec.Instancetype.Name)
+	if err != nil {
+		return nil, err
+	}
+	if !exists {
+		return m.findInstancetypeByClient(vm)
+	}
+	instancetype := obj.(*instancetypev1alpha2.VirtualMachineInstancetype)
```
Comment (0xFelix) [inline pkg/instancetype/instancetype.go:614]: Check the cast?

File: pkg/instancetype/instancetype.go [hunk 8]
```diff
@@ -516,11 +629,30 @@ func (m *methods) findClusterInstancetype(vm *virtv1.VirtualMachine) (*instancet
...
+
+func (m *methods) findClusterInstancetypeByInformer(vm *virtv1.VirtualMachine) (*instancetypev1alpha2.VirtualMachineClusterInstancetype, error) {
+	obj, exists, err := m.clusterInstancetypeStore.GetByKey(vm.Spec.Instancetype.Name)
 	if err != nil {
 		return nil, err
 	}
+	if !exists {
+		return m.findClusterInstancetypeByClient(vm)
+	}
+	instancetype := obj.(*instancetypev1alpha2.VirtualMachineClusterInstancetype)
```
Comment (0xFelix) [inline pkg/instancetype/instancetype.go:647]: Check the cast?

File: pkg/instancetype/instancetype_test.go [hunk 9]
```diff
@@ -287,6 +339,23 @@ var _ = Describe("Instancetype and Preferences", func() {
 				Expect(*instancetypeSpec).To(Equal(f.Spec))
 			})
 
+			It("uses client when instancetype not found within informer", func() {
+				err := clusterInstancetypeInformerStore.Delete(f)
+				Expect(err).ToNot(HaveOccurred())
+
+				instancetypeSpec, err := instancetypeMethods.FindInstancetypeSpec(vm)
+				Expect(err).ToNot(HaveOccurred())
+				Expect(*instancetypeSpec).To(Equal(f.Spec))
```
Comment (0xFelix) [inline pkg/instancetype/instancetype_test.go:348]: Just noticed the inconsistent naming of instancetypes/preferences. Sometimes the variable name assigned to in BeforeEach is longer and somethings shorter (`f`). Might make sense to use a consistent way of naming?

File: pkg/virt-api/rest/subresource.go [hunk 10]
```diff
@@ -90,7 +90,7 @@ func NewSubresourceAPIApp(virtCli kubecli.KubevirtClient, consoleServerPort int,
 	// the virtCli is nil, and accessing GeneratedKubeVirtClient() would cause nil dereference.
 	var instancetypeMethods instancetype.Methods
 	if virtCli != nil {
-		instancetypeMethods = instancetype.NewMethods(virtCli)
+		instancetypeMethods = instancetype.NewMethods(nil, nil, nil, nil, nil, virtCli)
```
Comment (0xFelix) [inline pkg/virt-api/rest/subresource.go:93]: This looks really weird to me. Can't the struct be used directly? Is there a benefit in using the `NewMethods` func?

**Review by 0xFelix — COMMENTED** [review]
I added some comments. Would it make sense to also add functional tests for the informers?

File: pkg/instancetype/instancetype.go [hunk 11]
```diff
@@ -421,17 +443,57 @@ func (m *methods) getPreferenceSpecRevision(revisionName string, namespace strin
 	}
 }
 
+func (m *methods) getControllerRevisionByInformer(revisionName, namespace string) (*appsv1.ControllerRevision, error) {
```
Comment (0xFelix) [inline pkg/instancetype/instancetype.go:446]: It might be helpful to use `types.NamespacedName` here?

https://pkg.go.dev/k8s.io/apimachinery/pkg/types#NamespacedName

File: pkg/virt-api/rest/subresource.go (hunk 10 above)
Comment (lyarwood) [reply pkg/virt-api/rest/subresource.go:95]: Apologies missed this, `methods` isn't public but that's something we could change so I really don't know tbh.

File: pkg/instancetype/instancetype_test.go (hunk 9 above)
Comment (lyarwood) [reply pkg/instancetype/instancetype_test.go:348]: I honestly thought we cleaned all of these up in an older cleanup series, I can sort this out in a fup.

**Review by davidvossel — COMMENTED** [review]
/approve

I didn't give this a detailed review, but I agree with the structure and concept. I'll let someone else provide the final lgtm.

I also wanted to point out that the performance data is interesting here. I'd surprised this offers such a significant improvement to the p95 startup time.

File: pkg/instancetype/instancetype_test.go [hunk 12]
```diff
@@ -155,6 +187,23 @@ var _ = Describe("Instancetype and Preferences", func() {
...
+
+				f, err := instancetypeMethods.FindInstancetypeSpec(vm)
+				Expect(err).ToNot(HaveOccurred())
+				Expect(*f).To(Equal(clusterInstancetype.Spec))
+			})
+
+			It("returns expected instancetype using only the client", func() {
+				instancetypeMethods = instancetype.NewMethods(nil, nil, nil, nil, nil, virtClient)
+
+				f, err := instancetypeMethods.FindInstancetypeSpec(vm)
```
Comment (0xFelix) [inline pkg/instancetype/instancetype_test.go:202]: Can you use the same naming scheme for the newly added tests as below and create a follow up PR to cleanup the existing ones?

File: pkg/virt-api/rest/subresource.go (hunk 10 above)
Comment (0xFelix) [reply pkg/virt-api/rest/subresource.go:95]: Can you investigate if this would be a lot of effort? Is there a benefit to hiding the actual struct?

File: pkg/instancetype/instancetype.go [hunk 13]
```diff
@@ -421,27 +444,93 @@ func (m *methods) getPreferenceSpecRevision(revisionName string, namespace strin
...
+		Name:      vm.Spec.Preference.Name,
+	}
+	if m.preferenceStore != nil {
+		return m.findPreferenceByInformer(namespacedName)
+	}
+	return m.findPreferenceByClient(namespacedName)
+}
 
-	preference, err := m.clientset.VirtualMachinePreference(vm.Namespace).Get(context.Background(), vm.Spec.Preference.Name, metav1.GetOptions{})
+func (m *methods) findPreferenceByInformer(namespacedName types.NamespacedName) (*instancetypev1alpha2.VirtualMachinePreference, error) {
```
[the remark this answers is not in the document]
Comment (lyarwood) [reply pkg/instancetype/instancetype.go:484]: ACK will address in a follow up PR.

File: pkg/instancetype/instancetype_test.go (hunk 12 above)
Comment (lyarwood) [reply pkg/instancetype/instancetype_test.go:202]: ACK will address in a follow up PR.

File: pkg/instancetype/instancetype.go (hunk 13 above)
[the remark this answers is not in the document]
Comment (lyarwood) [reply pkg/instancetype/instancetype.go:484]: https://github.com/kubevirt/kubevirt/pull/9067

File: pkg/instancetype/instancetype_test.go (hunk 12 above)
Comment (lyarwood) [reply pkg/instancetype/instancetype_test.go:202]: https://github.com/kubevirt/kubevirt/pull/9067

**Comment by lyarwood** [comment]
@davidvossel would you mind overriding the fossa job as per the upstream ML thread about the failure:

https://groups.google.com/g/kubevirt-dev/c/y8V9rDbdCw4

This PR is failing for the same problems with CDI:

https://app.fossa.com/projects/custom%2B13072%2Fgit%40github.com%3Akubevirt%2Fkubevirt.git/refs/branch/main/89ad4ac23dd238d021ef414364c3feb0445bc995/browse/dependencies/?flagged=true

**Comment by lyarwood** [comment]
/hold

```
pkg/storage/export/export/export.go:296:53: not enough arguments in call to instancetype.NewMethods
	have (kubecli.KubevirtClient)
	want ("kubevirt.io/kubevirt/vendor/k8s.io/client-go/tools/cache".Store, "kubevirt.io/kubevirt/vendor/k8s.io/client-go/tools/cache".Store, "kubevirt.io/kubevirt/vendor/k8s.io/client-go/tools/cache".Store, "kubevirt.io/kubevirt/vendor/k8s.io/client-go/tools/cache".Store, "kubevirt.io/kubevirt/vendor/k8s.io/client-go/tools/cache".Store, kubecli.KubevirtClient)
```

**Comment by lyarwood** [comment]
> /hold
> 
> ```
> pkg/storage/export/export/export.go:296:53: not enough arguments in call to instancetype.NewMethods
> 	have (kubecli.KubevirtClient)
> 	want ("kubevirt.io/kubevirt/vendor/k8s.io/client-go/tools/cache".Store, "kubevirt.io/kubevirt/vendor/k8s.io/client-go/tools/cache".Store, "kubevirt.io/kubevirt/vendor/k8s.io/client-go/tools/cache".Store, "kubevirt.io/kubevirt/vendor/k8s.io/client-go/tools/cache".Store, "kubevirt.io/kubevirt/vendor/k8s.io/client-go/tools/cache".Store, kubecli.KubevirtClient)
> ```
> 
> Caused by #8953 landing yesterday, I'll fix this up now.

/hold cancel

@awels  would you mind taking a look over https://github.com/kubevirt/kubevirt/pull/8537/commits/397e799c0b611f185ff405d1129b6c8f488e3db9 that switches the export controller over to using informers?

**Comment by awels** [comment]
The commit looks good to me

**Comment by 0xFelix** [comment]
/lgtm

Thanks!
