### PR TITLE
Remove the duplicity libvirt connection

### PR DESCRIPTION
**Pull request by petrkotas**
Code cleanup

The newConnection used to connect to the
libvirt is done twice, which is unnecesary.

It is removed and replaced with one attempt
with correct polling.

@rmohr @fabiand @davidvossel PRM

---
This change is [Reviewable](https://reviewable.io/reviews/kubevirt/kubevirt/493)

### CODE REVIEW

**Comment by rmohr** [comment]
ok to test

**Comment by stu-gott** [comment]
@petrkotas Just some background as to why the waitForLibvirt call exists. At one point during development, the libvirt contianer was added directly to the virt-handler pod. When that was the case, the container would usually crashloop because of a race condition. By adding this graceful delay, it made it possible to for virt-handler to start successfully on the first pass. When libvirt and virt-handler were in the same pod, this could take a dozen restarts for the situation to be resolved because libvirt would get restarted with the rest of the pod and the race would start over.

Even though it's less critical, this same situation still applies currently, but with libvirt in a separate pod than virt-handler, the situation will eventually resolve itself because libvirt can start and establish itself independently of virt-handler.

Personally I feel we should leave the waitForLibvirt codepath in place. You are correct that it is redundant from an overall number of connections standpoint, but it just feels cleaner and more stable to have each component come online without temporarily crashlooping a few times.

File: pkg/virt-handler/virtwrap/cli/libvirt.go [hunk 1]
```diff
@@ -318,29 +317,28 @@ type VirDomain interface {
...
+
+	err = utilwait.PollImmediate(interval, timeout, func() (done bool, err error) {
+		virConn, err = newConnection(uri, user, pass)
+		if err != nil {
+			return false, nil
+		}
+		return true, nil
+	})
 	if err != nil {
 		return nil, err
```
Comment (stu-gott) [inline pkg/virt-handler/virtwrap/cli/libvirt.go]: Previously we added context to this error message.

```fmt.Errorf("cannot connect to libvirt daemon: %v", err)```

Now that the PollImmediate logic has been moved here, we should move that message too. Otherwise the message that will bubble up with this error will be "timed out waiting for the condition", which is pretty generic and unhelpful.

File: pkg/virt-handler/virtwrap/cli/libvirt.go [hunk 2]
```diff
@@ -318,29 +317,28 @@ type VirDomain interface {
...
-			defer virConn.Close()
-			return true, nil
-		}
-		return false, nil
-	})
-}
-
 func NewConnection(uri string, user string, pass string, checkInterval time.Duration) (Connection, error) {
 	timeout := 15 * time.Second
+	interval := 10 * time.Second
```
Comment (stu-gott) [inline pkg/virt-handler/virtwrap/cli/libvirt.go]: Since you're in here fixing things, would you mind making `timeout` and `interval` be module level constants (possibly with a better name). It's just good form to keep arbitrary numbers highly visible.

Comment (petrkotas) [reply pkg/virt-handler/virtwrap/cli/libvirt.go]: Already on it.

**Comment by rmohr** [comment]
There seems to be a  unit test still in place which references `waitForLibvirt`.

```
pkg/virt-handler/virtwrap/cli/libvirt_suite_test.go:34: undefined: waitForLibvirt
```

File: pkg/virt-handler/virtwrap/cli/libvirt.go (hunk 1 above)
Comment (petrkotas) [reply pkg/virt-handler/virtwrap/cli/libvirt.go]: Done

**Comment by petrkotas** [comment]
Fixed the tests.

**Comment by stu-gott** [comment]
re-test this please

**Comment by stu-gott** [comment]
@petrkotas as near as I can tell it was a timeout during cleanup.

**Comment by davidvossel** [comment]
retest this please

**Comment by davidvossel** [comment]
retest this please

**Comment by rmohr** [comment]
The test failures will be fixed with #500 . "go test" has a default timeout of 10 minutes.
